# Generated by Django 4.2.4 on 2023-08-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('emp', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='timing_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('durations', models.IntegerField(null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thisapp.registermodel')),
            ],
        ),
    ]
