# Generated by Django 4.1.5 on 2023-08-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing_model',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thisapp.registermodel'),
        ),
    ]
