# Generated by Django 4.2.4 on 2023-08-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0002_alter_timing_model_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='emp',
            field=models.CharField(max_length=10),
        ),
    ]
