# Generated by Django 4.2.4 on 2023-08-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0004_alter_timing_model_durations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='emp',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
